### ISSUE TITLE
Expose ICertificateStore as public

### ISSUE THREAD

**Issue by twsouthwick** [natemcmaster/LetsEncrypt#34] opened 2020-01-02 20:07 UTC
I forked this a while back for an internal project and made `ICertificateStore` public. This allowed me to store in Azure KeyVault easily. This is really helpful for things like containers where they may be recycled at different times and not have to hit LetsEncrypt (and thus add towards the limit). Is there any issue with moving `ICertificateStore` to be public rather than internal? The methods should be made async as well so that remote stores would work ok.

**Comment by natemcmaster** [comment] 2020-01-03 04:32
This looks like a duplicate of #4. I pushed some changes in October to add `ICertificateRepository`, but haven't made a release yet.

Would you be willing to share your code to store a certificate to Azure Key Vault?

**Comment by twsouthwick** [comment] 2020-01-07 21:56
Cool - I hadn't seen ICertifiacte Repository. I'd be happy to share the code for key vault

**Comment by twsouthwick** [comment] 2020-01-07 22:36
Taking a look at `ICertificateRepository`, it doesn't allow for a load, which is still on `ICertificateStore`. Can this be combined? Is there a reason to keep the store a repository separate?

**Comment by natemcmaster** [comment] 2020-01-09 04:32
I'm still working on getting the abstraction right for loading certificates. I started working on this over the weekend in https://github.com/natemcmaster/LetsEncrypt/pull/41. I envisioned having separate interfaces, one for loading, one for saving, and you could implement both on one class if you want. Before I make an API public and released, I like to ensure the API works for the X509Store and directory scenarios and then move on to others like KeyVault.

**Comment by twsouthwick** [comment] 2020-01-10 17:24
Cool. One concernI have with the `ICertificateSource` is that it requires you to load all available certificates. In order to connect with KeyVault, this would require the `list` permission in addition to `get`. If the API can submit a domain name to retrieve, then it will limit the required permissions the app needs for KeyVault.

**Comment by natemcmaster** [comment] 2020-01-17 05:09
Thanks for the feedback! These suggestions are the reason I didn't release `ICertificateSource` as a public API.

In KeyVault, how do you fetch a specific certificate? Do you give KV the cert serial number? Common Name? Something else? Does KV allow you to fetch a certificate that has SubjectAltName's?

**Comment by twsouthwick** [comment] 2020-01-23 19:09
The certificate is named as it is put into KeyVault and can be anything (within the naming convention of KeyVault). The domain name is what I've been using and I just submit that to request it. You can have versions of it, but by default it returns the latest version.

**Comment by natemcmaster** [comment] 2020-01-28 05:59
Thought about this a little more. I think `ICertificateSource` can work for this scenario thanks to options classes and constructor injection. You raise a good concern, but is it still a problem if you consider the following pseudo implementation?
```c#

    public class AzureKeyVaultCertificateSource : ICertificateSource
    {
        private readonly IOptions<LetsEncryptOptions> _options;

        public AzureKeyVaultCertificateSource(IOptions<LetsEncryptOptions> options)
        {
            _options = options;
        }

        public async Task<IEnumerable<X509Certificate2>> GetCertificatesAsync(CancellationToken cancellationToken)
        {
            var certs = new List<X509Certificate2>();
            foreach (var domain in this._options.Value.DomainNames)
            {
                var cert = await GetCertificatesAsync(domain, cancellationToken);
                certs.Add(cert);
            }
            return certs;
        }

        private Task<X509Certificate2> GetCertificatesAsync(string domain, CancellationToken cancellationToken)
        {
            // connect to Azure Key Vault here to fetch a specific cert using domain name
            throw new NotImplementedException();
        }
    }
```

**Comment by twsouthwick** [comment] 2020-02-06 03:07
Sure, that looks reasonable. I'll adapt what I have to use that pattern.

**Closed** 2020-03-10 05:41 UTC
Labels: enhancement
